# Generated by Django 4.0.4 on 2022-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
